### ISSUE TITLE
lessons.md reviewed

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/git#41]
- Look at your workshop on [the website](http://kallewesterling.pythonanywhere.com) to see what your workshop currently looks like, and what looks like it needs to change.
- Think about order and transitions—do the lessons follow a logical pattern and is it working? Do you need to add something somewhere? Are the transitions between the lessons clear?
- Can you add a challenge at the end of the lesson that summarizes what the learner has learned, and activates the knowledge in an interactive way.
- Think about the length of the lessons — are they too long? Too short? In general, each lesson should cover one topic, or one particular skill — or perhaps connect two skills. If you find that you’re covering more than that in one lesson, perhaps they should be split into more than one.
- While reviewing the lessons.md file, think about vocabulary terms that we should add in an easily accessible "dictionary" for our learners.

Feel free to reach out to me and @lmrhody and ask for help, if you need it. Also feel free to involve others in the group!

**Comment by kallewesterling** [comment]
If you want another view of the Markdown and how it is being translated/parsed into the website, you can see [this link](https://kallewesterling.pythonanywhere.com/preview). It is a new tool that I created that will download the live markdown from GitHub and preview the way that the website interprets the markdown. In order to access it, you'll have to be logged in using `admin` as your login and `admin` as your password!

Once you're logged in, you can click "Preview in parser" and it should show you what the live markdown is, and how the website will interpret your markdown.

**Comment by paramajmera** [comment]
Here's my thoughts and suggestions for the git workshop - 

- I would recommend moving the green "get started" button to appear below the "contexts" section. When I went through the workshop the first couple of times, I did not notice the contexts section because I would just click get started and I never scrolled. The contexts section is really important and useful because it gives participants a sense of what to expect in this workshop as well as start thinking about ways in which git might be used.
- I think that there could be more emphasis on how git supports the collaborative writing of code and project management. This point must be stressed so that people have a stronger idea of why to use github in collaborative DH projects. Maybe this can be reiterated in the project management workshop.
- Another use of Github that could be further emphasized is that it is also used to store project documentation and protocols. See for example - https://bookworm-project.github.io/Docs/. 
- The note on syllabi (case 3, page 2) would be much stronger if it also contained links to people who actually use github to host their syllabi.
- It would be good to have a concluding section that wraps up the workshop more effectively. The way it currently ends is a bit abrupt. This concluding section might summarize the major ideas of the workshop and open pathways to thinking about how git can be of use in the partipants' local communities. Perhaps here we can have some thoughts and suggestions on using github to support remote collaborative work.

**Comment by rafadavis** [comment]
Good job, Kristen! I agree with Param's points above, and there are some things I would add:

- In "Case One: This Session", "If you look just under the workshop title, DHRI-Curriculum/git at the top of this page, you can see it is forked from pswee001/Git_DRI_Jan_2018":

  This sentence will not make sense if they are on the course webpage instead of the github page. I also think it is worth to have an image with the head of the page, circling the "forked from". The top of github pages are very busy and complicated for those who are new to it.

- In my personal opinion, git is the most complicated of the workshops we teach. It is very abstract, and people don't even know what they are trying to do. I think this workshop is doing a good job in introducing the concepts. The writing is good and clear. However, even with the best explanation, people will not get things until they do them, and do them multiple times.
I believe we should make that clear in the first section "What are Git, GitHub and Markdown?" saying something like "don't worry about understanding everything right now, this will make more sense later once you put it in practice."

  The sentence "As we move forward its important to make sure we're firm on the distinctions between the three different tools outlined above." might sound a bit discouraging. I don't really think one can be firm on the distinction between git and github before going through the workshop.

- I think the section about staging, commiting and pushing would benefit a lot from print screens. It will be a good way of showing the changes and show how the colors have meaning on git in the terminal. 

- In the following sentences, "-" should be an em-dash: 
  - "Use git add via the command line to stage the file - tell Git what document you want it to pay attention to." ;  
  - "A key advantage of the platform is that you can find lots of bits of software that do many different things - such as code for plugins for WordPress or Leaflet"; 
  - "Cloning a repository means making a copy of a repository on GitHub, to download and work on locally - on your local machine. By entering the following code into your terminal, you can clone any public directory on GitHub"; 
  - "You made it to the end of this workshop-congratulations!"

**Comment by hackettka** [comment]
Thanks @paramajmera and @rafadavis for your comments! I've incorporated some and added others as wish list items. Regardless, they've gone a long way in improving this workshop.
